workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

image: docker:24.0.7-dind

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  REGISTRY: docker.telepat.online
  COMPOSE_FILE: ./compose.prod.yaml
  SOURCE_COMMIT: $CI_COMMIT_SHA

stages:
  - build

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY

build:
  stage: build
  script:
    - touch .env
    - make build-prod-image
    - docker push docker.telepat.online/agents-scales-image:latest
