services:
  server:
    image: docker.telepat.online/agents-scales-image:latest
    container_name: agents-scales-server
    env_file:
      - .env
      - enviroments/scales.env
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}
      - DEBUG=false
      - HOST="${PROTOCOL}://scales.${AGENT_DOMAIN}"
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=80
    entrypoint: |
      /bin/sh -c '
      goose postgres "$(get_db_string)" -dir=migrations up
      server
      '
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - agents-net
    labels:
      - dev.dozzle.group=agents-pilldispenser
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - "80"

