services:
  server:
    container_name: medsenger-scales-server
    image: scales-bot
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: final
      network: "host"
      args:
        SOURCE_COMMIT: $SOURCE_COMMIT
    command: server
    restart: unless-stopped
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
