services:
  agents-scales:
    image: docker.telepat.online/agents-scales-image:latest
    container_name: agents-scales-server
    env_file:
      - .env
      - enviroments/scales.env
    environment:
      - HOST="${PROTOCOL}://scales.${AGENT_DOMAIN}"
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - agents-net
    labels:
      - dev.dozzle.group=agents-pilldispenser
      - com.centurylinklabs.watchtower.enable=true
