services:
  server:
    container_name: agents-scales-server
    image: docker.telepat.online/agents-scales-image:latest
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
