name: Mirror repository updates to gitlab

on:
  push:
  create:
  delete:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  mirror_to_gitlab:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - uses: action-pack/gitlab-sync@v3
        with:
          username: ${{ secrets.GITLAB_USERNAME }}
          url: ${{ secrets.GITLAB_URL }}
          token: ${{ secrets.GITLAB_TOKEN }}
